import { Card } from './types';

export const CARD_DECK: Card[] = [
  // --- DRINK (20 cards) ---
  { id: 1, category: 'drink', content: "Drink if you said 'I love you' first.", instruction: "Both play" },
  { id: 2, category: 'drink', content: "Drink if you are the messier one.", instruction: "Be honest!" },
  { id: 3, category: 'drink', content: "Drink if you forgot an anniversary.", instruction: "Both play" },
  { id: 4, category: 'drink', content: "Drink if you spend more time on your phone.", instruction: "Call each other out" },
  { id: 5, category: 'drink', content: "Drink if you are the better cook.", instruction: "Debate it, then drink" },
  { id: 6, category: 'drink', content: "Drink if you initiated the first kiss.", instruction: "Both play" },
  { id: 7, category: 'drink', content: "Drink if you have a secret tattoo.", instruction: "Reveal it or drink double" },
  { id: 8, category: 'drink', content: "Drink if you take longer to get ready.", instruction: "Both play" },
  { id: 9, category: 'drink', content: "Drink if you are more stubborn.", instruction: "Both play" },
  { id: 10, category: 'drink', content: "Drink if you've ever checked your partner's phone.", instruction: "Guilty?" },
  { id: 11, category: 'drink', content: "Drink if you are the big spoon usually.", instruction: "Cuddle up" },
  { id: 12, category: 'drink', content: "Drink if you made the first move.", instruction: "Cheers to bravery" },
  { id: 13, category: 'drink', content: "Drink if you handle the spiders.", instruction: "The hero drinks" },
  { id: 14, category: 'drink', content: "Drink if you usually pick the movie.", instruction: "Controller hog" },
  { id: 15, category: 'drink', content: "Drink if you have more shoes.", instruction: "Count 'em if you need to" },
  { id: 16, category: 'drink', content: "Drink if you're the better driver.", instruction: "Debatable?" },
  { id: 17, category: 'drink', content: "Drink if you steal the covers.", instruction: "Blanket thief" },
  { id: 18, category: 'drink', content: "Drink if you snore.", instruction: "Admit it" },
  { id: 19, category: 'drink', content: "Drink if you have more exes.", instruction: "Don't get jealous" },
  { id: 20, category: 'drink', content: "Drink if you earn more money.", instruction: "Sugar mommy/daddy" },

  // --- TRUTH (20 cards) ---
  { id: 21, category: 'truth', content: "What was your first impression of me?", instruction: "Share with partner" },
  { id: 22, category: 'truth', content: "What is your favorite body part of mine?", instruction: "Be specific" },
  { id: 23, category: 'truth', content: "When did you realize you loved me?", instruction: "Story time" },
  { id: 24, category: 'truth', content: "What is one thing you'd change about me?", instruction: "Tread carefully!" },
  { id: 25, category: 'truth', content: "What is your biggest fear in our relationship?", instruction: "Deep talk" },
  { id: 26, category: 'truth', content: "Describe our first date in 3 words.", instruction: "Go!" },
  { id: 27, category: 'truth', content: "What's the most annoying thing I do?", instruction: "Be nice" },
  { id: 28, category: 'truth', content: "Have you ever lied to get out of a date with me?", instruction: "Truth or drink" },
  { id: 29, category: 'truth', content: "Who is your celebrity hall pass?", instruction: "No jealousy allowed" },
  { id: 30, category: 'truth', content: "What's a fantasy you haven't told me yet?", instruction: "Whisper it" },
  { id: 31, category: 'truth', content: "If we could move anywhere, where would it be?", instruction: "Dream big" },
  { id: 32, category: 'truth', content: "What is my best quality?", instruction: "Compliment time" },
  { id: 33, category: 'truth', content: "What's the funniest thing I've ever done?", instruction: "Laugh about it" },
  { id: 34, category: 'truth', content: "What outfit of mine do you hate?", instruction: "Fashion police" },
  { id: 35, category: 'truth', content: "What's a secret you've kept from your parents?", instruction: "Spill the tea" },
  { id: 36, category: 'truth', content: "Who is the better kisser?", instruction: "Honesty hour" },
  { id: 37, category: 'truth', content: "What's the most embarrassing thing you've done in front of me?", instruction: "Cringe time" },
  { id: 38, category: 'truth', content: "If you could trade lives with me for a day, what would you do?", instruction: "Role reversal" },
  { id: 39, category: 'truth', content: "What's your favorite memory of us?", instruction: "Awww" },
  { id: 40, category: 'truth', content: "Am I a good sleeper or a nightmare?", instruction: "Sleep habits" },

  // --- DARE (20 cards) ---
  { id: 41, category: 'dare', content: "Give your partner a 1-minute massage.", instruction: "Shoulders or feet" },
  { id: 42, category: 'dare', content: "Let your partner post a status on your social media.", instruction: "Keep it up for 1 hour" },
  { id: 43, category: 'dare', content: "Do your best impression of your partner.", instruction: "Don't be mean!" },
  { id: 44, category: 'dare', content: "Whisper something dirty in your partner's ear.", instruction: "Make them blush" },
  { id: 45, category: 'dare', content: "Let your partner tickle you for 30 seconds.", instruction: "No escaping" },
  { id: 46, category: 'dare', content: "Swap an article of clothing with your partner.", instruction: "Fashion show" },
  { id: 47, category: 'dare', content: "Serenade your partner with a love song.", instruction: "Commit to the performance" },
  { id: 48, category: 'dare', content: "Do 10 pushups with your partner on your back (or try).", instruction: "Strength test" },
  { id: 49, category: 'dare', content: "Let your partner style your hair.", instruction: "Get creative" },
  { id: 50, category: 'dare', content: "Blindfold yourself and guess a body part by touch.", instruction: "Sensory game" },
  { id: 51, category: 'dare', content: "Twerk for 15 seconds.", instruction: "Shake it" },
  { id: 52, category: 'dare', content: "Speak in a foreign accent for the next 3 rounds.", instruction: "Oui oui" },
  { id: 53, category: 'dare', content: "Kiss your partner somewhere other than the lips.", instruction: "Be sweet" },
  { id: 54, category: 'dare', content: "Let your partner look through your photo gallery for 1 minute.", instruction: "No hiding" },
  { id: 55, category: 'dare', content: "Recreate your first kiss.", instruction: "Set the mood" },
  { id: 56, category: 'dare', content: "Eat a piece of food out of your partner's hand like a dog.", instruction: "Good boy/girl" },
  { id: 57, category: 'dare', content: "Slow dance to no music for 1 minute.", instruction: "Close contact" },
  { id: 58, category: 'dare', content: "Let your partner write on your arm with a pen.", instruction: "A tattoo or a message" },
  { id: 59, category: 'dare', content: "Stare into each other's eyes without blinking. Loser drinks.", instruction: "Staring contest" },
  { id: 60, category: 'dare', content: "Give your partner a lap dance (funny or serious).", instruction: "Show your moves" },

  // --- CHALLENGE / WILD (20 cards) ---
  { id: 61, category: 'challenge', content: "Rock, Paper, Scissors. Loser takes a shot.", instruction: "Best of 3" },
  { id: 62, category: 'challenge', content: "Thumb war! Loser finishes their drink.", instruction: "1, 2, 3, 4..." },
  { id: 63, category: 'challenge', content: "Exchange clothes (tops only). Keep them on for 2 rounds.", instruction: "Swap!" },
  { id: 64, category: 'challenge', content: "First one to laugh drinks.", instruction: "Make funny faces" },
  { id: 65, category: 'challenge', content: "Guess your partner's phone password. If wrong, drink.", instruction: "Security check" },
  { id: 66, category: 'challenge', content: "Arm wrestle. Loser does a dare of winner's choice.", instruction: "Muscle up" },
  { id: 67, category: 'challenge', content: "Both players drink.", instruction: "Cheers!" },
  { id: 68, category: 'challenge', content: "The person holding this card is the King/Queen. Partner must serve them for 2 rounds.", instruction: "Royalty" },
  { id: 69, category: 'challenge', content: "Create a secret handshake.", instruction: "You have 1 minute" },
  { id: 70, category: 'challenge', content: "Take a selfie kissing. Post it or drink.", instruction: "PDA Alert" },
  { id: 71, category: 'challenge', content: "Waterfall! Start drinking, partner can't stop until you do.", instruction: "Chug chug" },
  { id: 72, category: 'challenge', content: "Rhyme time. Pick a word. Back and forth. Loser drinks.", instruction: "Don't pause" },
  { id: 73, category: 'challenge', content: "Categories: 'Reasons we fight'. Loser drinks.", instruction: "Be fast" },
  { id: 74, category: 'challenge', content: "Sit on your partner's lap for the next 3 rounds.", instruction: "Cozy up" },
  { id: 75, category: 'challenge', content: "Feed your partner a snack using only your mouth.", instruction: "No hands!" },
  { id: 76, category: 'challenge', content: "Tell each other a joke. If you don't laugh, drink.", instruction: "Impress me" },
  { id: 77, category: 'challenge', content: "Draw your partner on a piece of paper (or napkin). Best one wins.", instruction: "Art contest" },
  { id: 78, category: 'challenge', content: "Play 'Never Have I Ever' (3 fingers). First to lose drinks.", instruction: "Quick round" },
  { id: 79, category: 'challenge', content: "Give your partner a piggyback ride around the room.", instruction: "Giddy up" },
  { id: 80, category: 'challenge', content: "Plank contest. Loser drinks.", instruction: "Abs of steel" },

  // --- SPICY / EXTRA (19 cards) ---
  { id: 81, category: 'wild', content: "Remove one piece of clothing.", instruction: "Strip poker style" },
  { id: 82, category: 'wild', content: "Kiss your partner's neck.", instruction: "Gentle" },
  { id: 83, category: 'wild', content: "Take a body shot off your partner.", instruction: "Salt and lime?" },
  { id: 84, category: 'wild', content: "Demonstrate your favorite sexual position (clothes on).", instruction: "Charades" },
  { id: 85, category: 'wild', content: "Make a moan sound. Best one wins.", instruction: "Be loud" },
  { id: 86, category: 'wild', content: "Guess the color of your partner's underwear. Wrong? Drink.", instruction: "Check to verify" },
  { id: 87, category: 'wild', content: "Nibble on your partner's ear.", instruction: "Tease" },
  { id: 88, category: 'wild', content: "Spank your partner 3 times.", instruction: "Naughty" },
  { id: 89, category: 'wild', content: "Use a pickup line on your partner. If they cringe, you drink.", instruction: "Smooth talker" },
  { id: 90, category: 'wild', content: "Send a risky text to your partner right now.", instruction: "Even if they are next to you" },
  { id: 91, category: 'wild', content: "Lick your lips while looking at your partner.", instruction: "Seduce them" },
  { id: 92, category: 'wild', content: "Describe your partner's smell.", instruction: "Weird or sweet?" },
  { id: 93, category: 'wild', content: "Kiss for 10 seconds without hands.", instruction: "Passionate" },
  { id: 94, category: 'wild', content: "Blindfold partner and feed them something. They guess what it is.", instruction: "Taste test" },
  { id: 95, category: 'wild', content: "Run your hands through your partner's hair.", instruction: "Relaxing" },
  { id: 96, category: 'wild', content: "Whisper what you want to do later.", instruction: "Future plans" },
  { id: 97, category: 'wild', content: "Kiss the inside of your partner's wrist.", instruction: "Sensitive spot" },
  { id: 98, category: 'wild', content: "Bite your lip and wink.", instruction: "Flirty face" },
  { id: 99, category: 'wild', content: "Wildcard: Make a rule for the rest of the game.", instruction: "The Boss" },
];